[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd wacebackend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd wacebackend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd wacebackend && python manage.py migrate && gunicorn wace_api.wsgi:application --bind 0.0.0.0:$PORT"