[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app/wacebackend"
DJANGO_SETTINGS_MODULE = "wace_api.settings_production"
DEBUG = "False"
USE_HTTPS = "False"
RAILWAY_ENVIRONMENT = "production"
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"